#ifndef BASICHISTOS_H
#define BASICHISTOS_H
#include <iostream>
#include <fstream>
#include <string>

using namespace std;

#include "TString.h"
#include "TH1F.h"
#include "TH2F.h"
#include <TROOT.h>
#include <TChain.h>
#include "Math/VectorUtil.h"
#include <TFile.h>

class BasicHistos {
  public :

  BasicHistos(){};

  virtual ~BasicHistos(){}
   void BookBasicHistos(int vIt, string process);
   void BookGroupHistos();
   void BookGenHistos(int vIt, string process);
   void BookTrackHistos();

   void BS(string label, float Lumi);
   void FillBasicHistos(int process, float scale);
   void FillElectronHistoMaps(int process, float scale);
   void FillGenHistos(int process, float scale);
   void FillBasicHistoMaps(int process,float scale);
   void FillBasicHistoMaps_2lep(int process,float scale);
   void MakeBasicPlots(string label);
   void MakeNormalizedPlots();
   void MakeBasicHistoVectors_bckgd();
   void MakeBasicHistoVectors_bckgd2();
   //void MakeBasicHistoVectors(int process, string name,float signalscale);
   void MakeGenHistoVectors(int process, string name,float signalscale);
   void MakeGenHisto_Plots(string label);
   void ClearHistVectors();
   void BookElectronHistos(int, std::string); 
   void Make2DMetPlots(int vIt, string label);
   void MakeElectronHistoVectors(int process, string name,float signalscale);
   void MakeElectronPlots(float Lumi, string label);
   void SaveRootFile(char* name);
   void BookSRHistos_signal(int vIt, string process);
   void BookSRHistos_bg();

   void FillSRHistos_1lep(int process,float scale);
   void FillSRHistos_2lep(int process,float scale);
   void FillSRHistos_ST(int process,float scale);         
   void FillSRHistos_WJets(int process,float scale);
   void FillSRHistos_Rare(int process,float scale);
   void FillSRHistos_Signal(int process,float scale);

   void FillSRHistos_Dilep(int process,float scale);
   void FillSRHistos_SingleLep_notfromtop(int process,float scale);
   void FillSRHistos_SingleLep_fromtop(int process,float scale);
   void FillSRHistos_Znunu(int process,float scale);
   void FillSRHistos_data(int process,float scale);
   void MakeBasicSRPlots(string label, float Lumi);
   void MakeBasicSRPlots2(string label, float Lumi);
   void MakeBasicHistoVectors(int process,string name,float signalscale);

     TH1F* wjets;
     TH1F* onelep;
     TH1F* znunu;
     TH1F* twolep;
     TH1F* wjets_err;
     TH1F* onelep_err;
     TH1F* znunu_err;
     TH1F* twolep_err;
     TH1F* data;
     void BookVariable();

   TH1F* MT_1lepttbar;
   TH1F* MT2W_1lepttbar;
   TH1F* Chi2_1lepttbar;
   TH1F* MinDPhi_1lepttbar;
   TH1F* HTratio_1lepttbar;
   TH1F* DRlepb_1lepttbar;
   TH1F* leadbpt_1lepttbar;
   TH1F* met_1lepttbar;
   TH1F* metphi_1lepttbar;
   TH1F* leppt_1lepttbar;
   TH1F* lepeta_1lepttbar;
   TH1F* lepphi_1lepttbar;
   TH1F* HT_1lepttbar;
   TH1F* njets_1lepttbar;
   TH1F* nbjets_1lepttbar;
   TH1F* njets_pt200_nobtags_1lepttbar;
   TH1F* leadISRjet_pt200_nobtags_1lepttbar;
   TH1F* METoverSqrtHT_1lepttbar;
   TH1F* Mlepb_1lepttbar;
   TH1F* genMlepb_1lepttbar;
   TH1F* M3b_1lepttbar;
   TH1F* jetpt_1lepttbar;
   TH1F* DPhiLepJet_1lepttbar;
   TH1F* leadjetpt_1lepttbar;
   TH1F* DPhiWLep_1lepttbar;
   TH1F* PZeta_TrkLep_1lepttbar;
   TH1F* PZetaVis_TrkLep_1lepttbar;
   TH1F* ak4_nef_1lepttbar;
   TH1F* ak4_cef_1lepttbar;
   TH1F* ak4_EF_1lepttbar;

   TH1F* MT_singletop;
   TH1F* MT2W_singletop;
   TH1F* Chi2_singletop;
   TH1F* MinDPhi_singletop;
   TH1F* HTratio_singletop;
   TH1F* DRlepb_singletop;
   TH1F* leadbpt_singletop;
   TH1F* met_singletop;
   TH1F* metphi_singletop;
   TH1F* leppt_singletop;
   TH1F* lepeta_singletop;
   TH1F* lepphi_singletop;
   TH1F* HT_singletop;
   TH1F* njets_singletop;
   TH1F* nbjets_singletop;
   TH1F* njets_pt200_nobtags_singletop;
   TH1F* leadISRjet_pt200_nobtags_singletop;
   TH1F* METoverSqrtHT_singletop;
   TH1F* Mlepb_singletop;
   TH1F* genMlepb_singletop;
   TH1F* M3b_singletop;
   TH1F* jetpt_singletop;
   TH1F* DPhiLepJet_singletop;
   TH1F* leadjetpt_singletop;
   TH1F* DPhiWLep_singletop;
   TH1F* PZeta_TrkLep_singletop;
   TH1F* PZetaVis_TrkLep_singletop;
   TH1F* ak4_nef_singletop;
   TH1F* ak4_cef_singletop;
   TH1F* ak4_EF_singletop;

   TH1F* MT_1lep;
   TH1F* MT2W_1lep;
   TH1F* Topness_1lep;
   TH1F* Topnessmod_1lep;
   TH1F* Chi2_1lep;
   TH1F* MinDPhi_1lep;
   TH1F* HTratio_1lep;
   TH1F* DRlepb_1lep;
   TH1F* leadbpt_1lep;
   TH1F* met_1lep;
   TH1F* metphi_1lep;
   TH1F* leppt_1lep;
   TH1F* lepeta_1lep;
   TH1F* lepphi_1lep;
   TH1F* HT_1lep;
   TH1F* njets_1lep;
   TH1F* nbjets_1lep;
   TH1F* njets_pt200_nobtags_1lep;
   TH1F* leadISRjet_pt200_nobtags_1lep;
   TH1F* METoverSqrtHT_1lep;
   TH1F* Mlepb_1lep;
   TH1F* genMlepb_1lep;
   TH1F* M3b_1lep;
   TH1F* jetpt_1lep;
   TH1F* DPhiLepJet_1lep;
   TH1F* leadjetpt_1lep;
   TH1F* DPhiWLep_1lep;
   TH1F* PZeta_TrkLep_1lep; 
   TH1F* PZetaVis_TrkLep_1lep; 
   TH1F* ak4_nef_1lep;
   TH1F* ak4_cef_1lep;
   TH1F* ak4_EF_1lep;
   TH1F* Wpt_1lep;

   TH1F* MT_ST;
   TH1F* MT2W_ST;
   TH1F* Topness_ST;
   TH1F* Topnessmod_ST;
   TH1F* Chi2_ST;
   TH1F* MinDPhi_ST;
   TH1F* HTratio_ST;
   TH1F* DRlepb_ST;
   TH1F* leadbpt_ST;
   TH1F* met_ST;
   TH1F* metphi_ST;
   TH1F* leppt_ST;
   TH1F* lepeta_ST;
   TH1F* lepphi_ST;
   TH1F* HT_ST;
   TH1F* njets_ST;
   TH1F* nbjets_ST;
   TH1F* njets_pt200_nobtags_ST;
   TH1F* leadISRjet_pt200_nobtags_ST;
   TH1F* METoverSqrtHT_ST;
   TH1F* Mlepb_ST;
   TH1F* genMlepb_ST;
   TH1F* M3b_ST;
   TH1F* jetpt_ST;
   TH1F* DPhiLepJet_ST;
   TH1F* leadjetpt_ST;
   TH1F* DPhiWLep_ST;
   TH1F* PZeta_TrkLep_ST;
   TH1F* PZetaVis_TrkLep_ST;
   TH1F* ak4_nef_ST;
   TH1F* ak4_cef_ST;
   TH1F* ak4_EF_ST;
   TH1F* Wpt_ST;

   TH1F* MT_2lep;
   TH1F* MT2W_2lep;
   TH1F* Topness_2lep;
   TH1F* Topnessmod_2lep;
   TH1F* Chi2_2lep;
   TH1F* MinDPhi_2lep;
   TH1F* HTratio_2lep;
   TH1F* DRlepb_2lep;
   TH1F* leadbpt_2lep;
   TH1F* met_2lep;
   TH1F* metphi_2lep;
   TH1F* leppt_2lep;
   TH1F* lepeta_2lep;
   TH1F* lepphi_2lep;
   TH1F* HT_2lep;
   TH1F* njets_2lep;
   TH1F* nbjets_2lep;
   TH1F* njets_pt200_nobtags_2lep;
   TH1F* leadISRjet_pt200_nobtags_2lep;
   TH1F* METoverSqrtHT_2lep;
   TH1F* Mlepb_2lep;
   TH1F* genMlepb_2lep;
   TH1F* M3b_2lep;
   TH1F* jetpt_2lep;
   TH1F* DPhiLepJet_2lep;
   TH1F* leadjetpt_2lep;
   TH1F* DPhiWLep_2lep;
   TH1F* PZeta_TrkLep_2lep;
   TH1F* PZetaVis_TrkLep_2lep;
   TH1F* ak4_nef_2lep;
   TH1F* ak4_cef_2lep;
   TH1F* ak4_EF_2lep;
   TH1F* Wpt_2lep;

   TH1F* genHT_wjets;
   TH1F* MT_wjets;
   TH1F* MT2W_wjets;
   TH1F* Topness_wjets;
   TH1F* Topnessmod_wjets;
   TH1F* Chi2_wjets;
   TH1F* MinDPhi_wjets;
   TH1F* HTratio_wjets;
   TH1F* DRlepb_wjets;
   TH1F* leadbpt_wjets;
   TH1F* met_wjets;
   TH1F* metphi_wjets;
   TH1F* leppt_wjets;
   TH1F* lepeta_wjets;
   TH1F* lepphi_wjets;
   TH1F* HT_wjets;
   TH1F* njets_wjets;
   TH1F* nbjets_wjets;
   TH1F* njets_pt200_nobtags_wjets;
   TH1F* leadISRjet_pt200_nobtags_wjets;
   TH1F* METoverSqrtHT_wjets;
   TH1F* Mlepb_wjets;
   TH1F* genMlepb_wjets;
   TH1F* M3b_wjets;
   TH1F* jetpt_wjets;
   TH1F* DPhiLepJet_wjets;
   TH1F* leadjetpt_wjets;
   TH1F* DPhiWLep_wjets;
   TH1F* PZeta_TrkLep_wjets; 
   TH1F* PZetaVis_TrkLep_wjets; 
   TH1F* ak4_nef_wjets;
   TH1F* ak4_cef_wjets;
   TH1F* ak4_EF_wjets;
   TH1F* Wpt_wjets;

   TH1F* MT_rare;
   TH1F* MT2W_rare;
   TH1F* Topness_rare;
   TH1F* Topnessmod_rare;
   TH1F* Chi2_rare;
   TH1F* MinDPhi_rare;
   TH1F* HTratio_rare;
   TH1F* DRlepb_rare;
   TH1F* leadbpt_rare;
   TH1F* met_rare;
   TH1F* metphi_rare;
   TH1F* leppt_rare;
   TH1F* lepeta_rare;
   TH1F* lepphi_rare;
   TH1F* HT_rare;
   TH1F* njets_rare;
   TH1F* nbjets_rare;
   TH1F* njets_pt200_nobtags_rare;
   TH1F* leadISRjet_pt200_nobtags_rare;
   TH1F* METoverSqrtHT_rare;
   TH1F* Mlepb_rare;
   TH1F* genMlepb_rare;
   TH1F* M3b_rare;
   TH1F* jetpt_rare;
   TH1F* DPhiLepJet_rare;
   TH1F* leadjetpt_rare;
   TH1F* DPhiWLep_rare;
   TH1F* PZeta_TrkLep_rare; 
   TH1F* PZetaVis_TrkLep_rare; 
   TH1F* ak4_nef_rare;
   TH1F* ak4_cef_rare;
   TH1F* ak4_EF_rare;
   TH1F* Wpt_rare;

   TH1F* MT_data;
   TH1F* MT2W_data;
   TH1F* Topness_data;
   TH1F* Topnessmod_data;
   TH1F* Chi2_data;
   TH1F* MinDPhi_data;
   TH1F* HTratio_data;
   TH1F* DRlepb_data;
   TH1F* leadbpt_data;
   TH1F* met_data;
   TH1F* metphi_data;
   TH1F* leppt_data;
   TH1F* lepeta_data;
   TH1F* lepphi_data;
   TH1F* HT_data;
   TH1F* njets_data;
   TH1F* nbjets_data;
   TH1F* njets_pt200_nobtags_data;
   TH1F* leadISRjet_pt200_nobtags_data;
   TH1F* METoverSqrtHT_data;
   TH1F* Mlepb_data;
   TH1F* genMlepb_data;
   TH1F* M3b_data;
   TH1F* jetpt_data;
   TH1F* DPhiLepJet_data;
   TH1F* leadjetpt_data;
   TH1F* DPhiWLep_data;
   TH1F* PZeta_TrkLep_data;
   TH1F* PZetaVis_TrkLep_data;
   TH1F* ak4_nef_data;
   TH1F* ak4_cef_data;
   TH1F* ak4_EF_data;
   TH1F* Wpt_data;

   TH1F* MT_Dilep;
   TH1F* MT2W_Dilep;
   TH1F* Topness_Dilep;
   TH1F* Topnessmod_Dilep;
   TH1F* Chi2_Dilep;
   TH1F* MinDPhi_Dilep;
   TH1F* HTratio_Dilep;
   TH1F* DRlepb_Dilep;
   TH1F* leadbpt_Dilep;
   TH1F* met_Dilep;
   TH1F* metphi_Dilep;
   TH1F* leppt_Dilep;
   TH1F* lepeta_Dilep;
   TH1F* lepphi_Dilep;
   TH1F* HT_Dilep;
   TH1F* njets_Dilep;
   TH1F* nbjets_Dilep;
   TH1F* njets_pt200_nobtags_Dilep;
   TH1F* leadISRjet_pt200_nobtags_Dilep;
   TH1F* METoverSqrtHT_Dilep;
   TH1F* Mlepb_Dilep;
   TH1F* genMlepb_Dilep;
   TH1F* M3b_Dilep;
   TH1F* jetpt_Dilep;
   TH1F* DPhiLepJet_Dilep;
   TH1F* leadjetpt_Dilep;
   TH1F* DPhiWLep_Dilep;
   TH1F* PZeta_TrkLep_Dilep;
   TH1F* PZetaVis_TrkLep_Dilep;
   TH1F* ak4_nef_Dilep;
   TH1F* ak4_cef_Dilep;
   TH1F* ak4_EF_Dilep;
   TH1F* Wpt_Dilep;

   TH1F* MT_SingleLep_notfromtop;
   TH1F* MT2W_SingleLep_notfromtop;
   TH1F* Topness_SingleLep_notfromtop;
   TH1F* Topnessmod_SingleLep_notfromtop;
   TH1F* Chi2_SingleLep_notfromtop;
   TH1F* MinDPhi_SingleLep_notfromtop;
   TH1F* HTratio_SingleLep_notfromtop;
   TH1F* DRlepb_SingleLep_notfromtop;
   TH1F* leadbpt_SingleLep_notfromtop;
   TH1F* met_SingleLep_notfromtop;
   TH1F* metphi_SingleLep_notfromtop;
   TH1F* leppt_SingleLep_notfromtop;
   TH1F* lepeta_SingleLep_notfromtop;
   TH1F* lepphi_SingleLep_notfromtop;
   TH1F* HT_SingleLep_notfromtop;
   TH1F* njets_SingleLep_notfromtop;
   TH1F* nbjets_SingleLep_notfromtop;
   TH1F* njets_pt200_nobtags_SingleLep_notfromtop;
   TH1F* leadISRjet_pt200_nobtags_SingleLep_notfromtop;
   TH1F* METoverSqrtHT_SingleLep_notfromtop;
   TH1F* Mlepb_SingleLep_notfromtop;
   TH1F* genMlepb_SingleLep_notfromtop;
   TH1F* M3b_SingleLep_notfromtop;
   TH1F* jetpt_SingleLep_notfromtop;
   TH1F* DPhiLepJet_SingleLep_notfromtop;
   TH1F* leadjetpt_SingleLep_notfromtop;
   TH1F* DPhiWLep_SingleLep_notfromtop;
   TH1F* PZeta_TrkLep_SingleLep_notfromtop;
   TH1F* PZetaVis_TrkLep_SingleLep_notfromtop;
   TH1F* ak4_nef_SingleLep_notfromtop;
   TH1F* ak4_cef_SingleLep_notfromtop;
   TH1F* ak4_EF_SingleLep_notfromtop;
   TH1F* Wpt_SingleLep_notfromtop;

   TH1F* eventswithb_met_notfromtop;
   TH1F* eventswithc_met_notfromtop;
   TH1F* eventswithlf_met_notfromtop;

   TH1F* MT_SingleLep_fromtop;
   TH1F* MT2W_SingleLep_fromtop;
   TH1F* Topness_SingleLep_fromtop;
   TH1F* Topnessmod_SingleLep_fromtop;
   TH1F* Chi2_SingleLep_fromtop;
   TH1F* MinDPhi_SingleLep_fromtop;
   TH1F* HTratio_SingleLep_fromtop;
   TH1F* DRlepb_SingleLep_fromtop;
   TH1F* leadbpt_SingleLep_fromtop;
   TH1F* met_SingleLep_fromtop;
   TH1F* metphi_SingleLep_fromtop;
   TH1F* leppt_SingleLep_fromtop;
   TH1F* lepeta_SingleLep_fromtop;
   TH1F* lepphi_SingleLep_fromtop;
   TH1F* HT_SingleLep_fromtop;
   TH1F* njets_SingleLep_fromtop;
   TH1F* nbjets_SingleLep_fromtop;
   TH1F* njets_pt200_nobtags_SingleLep_fromtop;
   TH1F* leadISRjet_pt200_nobtags_SingleLep_fromtop;
   TH1F* METoverSqrtHT_SingleLep_fromtop;
   TH1F* Mlepb_SingleLep_fromtop;
   TH1F* genMlepb_SingleLep_fromtop;
   TH1F* M3b_SingleLep_fromtop;
   TH1F* jetpt_SingleLep_fromtop;
   TH1F* DPhiLepJet_SingleLep_fromtop;
   TH1F* leadjetpt_SingleLep_fromtop;
   TH1F* DPhiWLep_SingleLep_fromtop;
   TH1F* PZeta_TrkLep_SingleLep_fromtop;
   TH1F* PZetaVis_TrkLep_SingleLep_fromtop;
   TH1F* ak4_nef_SingleLep_fromtop;
   TH1F* ak4_cef_SingleLep_fromtop;
   TH1F* ak4_EF_SingleLep_fromtop;
   TH1F* Wpt_SingleLep_fromtop;

   TH1F* MT_Znunu;
   TH1F* MT2W_Znunu;
   TH1F* Topness_Znunu;
   TH1F* Topnessmod_Znunu;
   TH1F* Chi2_Znunu;
   TH1F* MinDPhi_Znunu;
   TH1F* HTratio_Znunu;
   TH1F* DRlepb_Znunu;
   TH1F* leadbpt_Znunu;
   TH1F* met_Znunu;
   TH1F* metphi_Znunu;
   TH1F* leppt_Znunu;
   TH1F* lepeta_Znunu;
   TH1F* lepphi_Znunu;
   TH1F* HT_Znunu;
   TH1F* njets_Znunu;
   TH1F* nbjets_Znunu;
   TH1F* njets_pt200_nobtags_Znunu;
   TH1F* leadISRjet_pt200_nobtags_Znunu;
   TH1F* METoverSqrtHT_Znunu;
   TH1F* Mlepb_Znunu;
   TH1F* genMlepb_Znunu;
   TH1F* M3b_Znunu;
   TH1F* jetpt_Znunu;
   TH1F* DPhiLepJet_Znunu;
   TH1F* leadjetpt_Znunu;
   TH1F* DPhiWLep_Znunu;
   TH1F* PZeta_TrkLep_Znunu;
   TH1F* PZetaVis_TrkLep_Znunu;
   TH1F* ak4_nef_Znunu;
   TH1F* ak4_cef_Znunu;
   TH1F* ak4_EF_Znunu;
   TH1F* Wpt_Znunu;

  TH1F* t_pt_MT100;
  TH1F* t_pt_MT300;
  TH1F* t_pt_ratio;
  TH1F* nTops_2lep;

   std::vector < TH1F* > _mymetVector;
   std::vector < TH1F* > _mymetphiVector;
   std::vector < TH1F* > _myrawmetVector;
   std::vector < TH1F* > _myrawmetphiVector;
   std::vector < TH1F* > _myjecmetVector;
   std::vector < TH1F* > _myjecmetXVector;
   std::vector < TH1F* > _myjecmetYVector;
   std::vector < TH1F* > _myjecmetphiVector;
   std::vector < TH1F* > _myunjecmetVector;
   std::vector < TH1F* > _myunjecmetphiVector;
   std::vector < TH1F* > _mycalometVector;
   std::vector < TH1F* > _mycalometphiVector;
   std::vector < TH1F* > _mytrkmetVector;
   std::vector < TH1F* > _mytrkmetphiVector;
   std::vector < TH1F* > _mylepptVector;
   std::vector < TH1F* > _myleprelisoVector;
   std::vector < TH1F* > _mylepminirelisoVector;
   std::vector < TH1F* > _mylepabsisoVector;
   std::vector < TH1F* > _mylepminiabsisoVector;
   std::vector < TH1F* > _mylepetaVector;
   std::vector < TH1F* > _mylepphiVector;
   std::vector < TH1F* > _myHTVector;
   std::vector < TH1F* > _myNGoodVtxVector;
   std::vector < TH1F* > _mynjetsVector;
   std::vector < TH1F* > _mynhfjetsVector;
   std::vector < TH1F* > _mynbjetsVector;
   std::vector < TH1F* > _mynjets_pt200_nobtagsVector;
   std::vector < TH1F* > _myleadISRjet_pt200_nobtagsVector;
   std::vector < TH1F* > _myMEToverSqrtHTVector;
   std::vector < TH1F* > _myMlepbVector;
   std::vector < TH1F* > _mygenMlepbVector;
   std::vector < TH1F* > _myM3bVector;
   std::vector < TH1F* > _myjetptVector;
   std::vector < TH1F* > _myjetetaVector;
   std::vector < TH1F* > _myjetphiVector;
   std::vector < TH1F* > _myDPhiLepJetVector;
   std::vector < TH1F* > _myleadjetptVector;
   std::vector < TH1F* > _myDPhiWLep;
   std::vector < TH1F* > _myWptVector;
   std::vector < TH1F* > _myPZeta_TrkLep; 
   std::vector < TH1F* > _myPZetaVis_TrkLep;
   std::vector < TH1F* > _myak4NEFVector;
   std::vector < TH1F* > _myak4CEFVector;
   std::vector < TH1F* > _myak4EFVector;

   std::vector < TH1F* > _mydetainVector;
   std::vector < TH1F* > _mydphiinVector;
   std::vector < TH1F* > _mysigmaietaietaVector;
   std::vector < TH1F* > _myhovereVector;
   std::vector < TH1F* > _mydzVector;
   std::vector < TH1F* > _myd0Vector;
   std::vector < TH1F* > _myempVector;
   std::vector < TH1F* > _myminirelisoVector;
   std::vector < TH1F* > _mymissinghitsVector;
   std::vector < TH1F* > _myconversionsvetoVector;

   std::vector < TH1F* > _mygenlepptVector;
   std::vector < TH1F* > _mygenlepetaVector;
   std::vector < TH1F* > _mygenNLepsVector;

    TH2F* jetPt2D_2lep;
    TH2F* Mlepb2D_2lep;
    TH2F* genMlepb2D_2lep;
    TH2F* genHT_recoHT;

    std::map<int, TH2F*> _theMET2DHistoMap;
    std::map<int, TH2F*> _theIso2DHistoMap;
    std::map<int, TH2F*> _thejetPt2DHistoMap;
    std::map<int, TH2F*> _theMlepb2DHistoMap;
    std::map<int, TH2F*> _thegenMlepb2DHistoMap;
//     std::map<int, string> _theNameMap;            
//     std::map<int, float> _theScalesMap;
     std::map<int, TH1F*> _theMTHistoMap;
     std::map<int, TH1F*> _theMTMHTHistoMap;
     std::map<int, TH1F*> _theMTnewmetHistoMap;
     std::map<int, TH1F*> _theMTrawmetHistoMap;
     std::map<int, TH1F*> _theMTHistoMap_2lep;
     std::map<int, TH1F*> _theMT2WHistoMap;
     std::map<int, TH1F*> _theMT2WHistoMap_2lep;
     std::map<int, TH1F*> _theTopnessHistoMap;
     std::map<int, TH1F*> _theTopnessmodHistoMap;
     std::map<int, TH1F*> _theTopnessHistoMap_2lep;
     std::map<int, TH1F*> _theTopnessmodHistoMap_2lep;
     std::map<int, TH1F*> _theChi2HistoMap;
     std::map<int, TH1F*> _theChi2HistoMap_2lep;
     std::map<int, TH1F*> _theMinDPhiHistoMap;
     std::map<int, TH1F*> _theMinDPhiHistoMap_2lep;
     std::map<int, TH1F*> _theHTratioHistoMap;
     std::map<int, TH1F*> _theHTratioHistoMap_2lep;
     std::map<int, TH1F*> _theDRlepbHistoMap;
     std::map<int, TH1F*> _theDRlepbHistoMap_2lep;
     std::map<int, TH1F*> _theleadbptHistoMap;
     std::map<int, TH1F*> _theleadbptHistoMap_2lep;
     std::map<int, TH1F*> _themetHistoMap;
     std::map<int, TH1F*> _themetHistoMap_2lep;
     std::map<int, TH1F*> _themetphiHistoMap;
     std::map<int, TH1F*> _themetphiHistoMap_2lep;
     std::map<int, TH1F*> _therawmetHistoMap;
     std::map<int, TH1F*> _therawmetHistoMap_2lep;
     std::map<int, TH1F*> _therawmetphiHistoMap;
     std::map<int, TH1F*> _therawmetphiHistoMap_2lep;
     std::map<int, TH1F*> _thejecmetHistoMap;
     std::map<int, TH1F*> _thejecmetXHistoMap;
     std::map<int, TH1F*> _thejecmetYHistoMap;
     std::map<int, TH1F*> _thejecmetHistoMap_2lep;
     std::map<int, TH1F*> _thejecmetphiHistoMap;
     std::map<int, TH1F*> _thejecmetphiHistoMap_2lep;
     std::map<int, TH1F*> _theunjecmetHistoMap;
     std::map<int, TH1F*> _theunjecmetHistoMap_2lep;
     std::map<int, TH1F*> _theunjecmetphiHistoMap;
     std::map<int, TH1F*> _theunjecmetphiHistoMap_2lep;
     std::map<int, TH1F*> _thecalometHistoMap;
     std::map<int, TH1F*> _thecalometHistoMap_2lep;
     std::map<int, TH1F*> _thecalometphiHistoMap;
     std::map<int, TH1F*> _thecalometphiHistoMap_2lep;
     std::map<int, TH1F*> _thetrkmetHistoMap;
     std::map<int, TH1F*> _thetrkmetHistoMap_2lep;
     std::map<int, TH1F*> _thetrkmetphiHistoMap;
     std::map<int, TH1F*> _thetrkmetphiHistoMap_2lep;    
     std::map<int, TH1F*> _thelepptHistoMap;
     std::map<int, TH1F*> _theleprelisoHistoMap;
     std::map<int, TH1F*> _thelepminirelisoHistoMap;
     std::map<int, TH1F*> _thelepabsisoHistoMap;
     std::map<int, TH1F*> _thelepminiabsisoHistoMap;
     std::map<int, TH1F*> _thelepptHistoMap_2lep;
     std::map<int, TH1F*> _thelepetaHistoMap;
     std::map<int, TH1F*> _thelepetaHistoMap_2lep;
     std::map<int, TH1F*> _thelepphiHistoMap;
     std::map<int, TH1F*> _thelepphiHistoMap_2lep;
     std::map<int, TH1F*> _theHTHistoMap;
     std::map<int, TH1F*> _theHTHistoMap_2lep;
     std::map<int, TH1F*> _theNGoodVtxHistoMap;
     std::map<int, TH1F*> _theNGoodVtxHistoMap_2lep;
     std::map<int, TH1F*> _thenjetsHistoMap;
     std::map<int, TH1F*> _thenhfjetsHistoMap;
     std::map<int, TH1F*> _thenjetsHistoMap_2lep;
     std::map<int, TH1F*> _thenbjetsHistoMap;
     std::map<int, TH1F*> _thenbjetsHistoMap_2lep;
     std::map<int, TH1F*> _thenjets_pt200_nobtagsHistoMap;
     std::map<int, TH1F*> _thenjets_pt200_nobtagsHistoMap_2lep;
     std::map<int, TH1F*> _theleadISRjet_pt200_nobtagsHistoMap;
     std::map<int, TH1F*> _theleadISRjet_pt200_nobtagsHistoMap_2lep;
     std::map<int, TH1F*> _theMEToverSqrtHTHistoMap;
     std::map<int, TH1F*> _theMEToverSqrtHTHistoMap_2lep;
     std::map<int, TH1F*> _theMlepbHistoMap;
     std::map<int, TH1F*> _theMlepbHistoMap_2lep;
     std::map<int, TH1F*> _thegenMlepbHistoMap;
     std::map<int, TH1F*> _thegenMlepbHistoMap_2lep;
     std::map<int, TH1F*> _theM3bHistoMap;
     std::map<int, TH1F*> _theM3bHistoMap_2lep;
     std::map<int, TH1F*> _thejetptHistoMap;
     std::map<int, TH1F*> _thejetetaHistoMap;
     std::map<int, TH1F*> _thejetphiHistoMap;
     std::map<int, TH1F*> _thejetptHistoMap_2lep;
     std::map<int, TH1F*> _theDPhiLepJetHistoMap;
     std::map<int, TH1F*> _theDPhiLepJetHistoMap_2lep;
     std::map<int, TH1F*> _theleadjetptHistoMap;
     std::map<int, TH1F*> _theleadjetptHistoMap_2lep;     

   std::map < int, TH1F* > _thedetainHistoMap;
   std::map < int, TH1F* > _thedphiinHistoMap;
   std::map < int, TH1F* > _thesigmaietaietaHistoMap;
   std::map < int, TH1F* > _thehovereHistoMap;
   std::map < int, TH1F* > _thedzHistoMap;
   std::map < int, TH1F* > _thed0HistoMap;
   std::map < int, TH1F* > _theempHistoMap;
   std::map < int, TH1F* > _theminirelisoHistoMap;
   std::map < int, TH1F* > _themissinghitsHistoMap;
   std::map < int, TH1F* > _theconversionsvetoHistoMap;

    std::map<int, TH1F*> _theTrackAbsIsoHistoMap;
    std::map<int, TH1F*> _theTrackRelIsoHistoMap;
    std::map<int, TH1F*> _theTrackIso_ntracks_HistoMap;
    std::map<int, TH1F*> _theTrackLep_ChargeHistoMap;
    std::map<int, TH1F*> _theTrackptHistoMap;
    std::map<int, TH1F*> _theTracketaHistoMap;
    std::map<int, TH1F*> _thecosDphiLepTrackHistoMap;

    std::map<int, TH1F*> _theDPhiWLepHistoMap;
    std::map<int, TH1F*> _theDPhiWLepHistoMap_2lep;
    std::map<int, TH1F*> _theWptHistoMap;
    std::map<int, TH1F*> _theWptHistoMap_2lep;
    std::map<int, TH1F*> _thePZeta_TrkLepHistoMap;
    std::map<int, TH1F*> _thePZetaVis_TrkLepHistoMap;
    std::map<int, TH1F*> _thePZeta_TrkLepHistoMap_2lep;
    std::map<int, TH1F*> _thePZetaVis_TrkLepHistoMap_2lep;
    std::map<int, TH1F*> _theak4NEFHistoMap;
    std::map<int, TH1F*> _theak4CEFHistoMap;
    std::map<int, TH1F*> _theak4EFHistoMap;

    std::map<int, TH1F*> _theak4NEFHistoMap_2lep;
    std::map<int, TH1F*> _theak4CEFHistoMap_2lep;
    std::map<int, TH1F*> _theak4EFHistoMap_2lep;

     std::map<int, TH1F*> _thegenlepptHistoMap;
     std::map<int, TH1F*> _thegenlepetaHistoMap;
     std::map<int, TH1F*> _thegenNLepsHistoMap;

    std::map<int, TH1F*> _theGenElAbsIsoHistoMap_2lep;
    std::map<int, TH1F*> _theGenElRelIsoHistoMap_2lep;
    std::map<int, TH1F*> _theGenElIso_ntracks_HistoMap_2lep;
    std::map<int, TH1F*> _theGenElLep_ChargeHistoMap_2lep;
    std::map<int, TH1F*> _theGenElptHistoMap_2lep;
    std::map<int, TH1F*> _theGenEletaHistoMap_2lep;
    std::map<int, TH1F*> _thecosDphiLepGenElHistoMap_2lep;

    std::map<int, TH1F*> _theGenMuAbsIsoHistoMap_2lep;
    std::map<int, TH1F*> _theGenMuRelIsoHistoMap_2lep;
    std::map<int, TH1F*> _theGenMuIso_ntracks_HistoMap_2lep;
    std::map<int, TH1F*> _theGenMuLep_ChargeHistoMap_2lep;
    std::map<int, TH1F*> _theGenMuptHistoMap_2lep;
    std::map<int, TH1F*> _theGenMuetaHistoMap_2lep;
    std::map<int, TH1F*> _thecosDphiLepGenMuHistoMap_2lep;

    std::map<int, TH1F*> _theGen3prongTauAbsIsoHistoMap_2lep;
    std::map<int, TH1F*> _theGen3prongTauRelIsoHistoMap_2lep;
    std::map<int, TH1F*> _theGen3prongTauIso_ntracks_HistoMap_2lep;
    std::map<int, TH1F*> _theGen3prongTauLep_ChargeHistoMap_2lep;
    std::map<int, TH1F*> _theGen3prongTauptHistoMap_2lep;
    std::map<int, TH1F*> _theGen3prongTauetaHistoMap_2lep;
    std::map<int, TH1F*> _thecosDphiLepGen3prongTauHistoMap_2lep;

    std::map<int, TH1F*> _theGen1prongTauAbsIsoHistoMap_2lep;
    std::map<int, TH1F*> _theGen1prongTauRelIsoHistoMap_2lep;
    std::map<int, TH1F*> _theGen1prongTauIso_ntracks_HistoMap_2lep;
    std::map<int, TH1F*> _theGen1prongTauLep_ChargeHistoMap_2lep;
    std::map<int, TH1F*> _theGen1prongTauptHistoMap_2lep;
    std::map<int, TH1F*> _theGen1prongTauetaHistoMap_2lep;
    std::map<int, TH1F*> _thecosDphiLepGen1prongTauHistoMap_2lep;
   
    std::vector < TH1F* > _theGenAbsIsoVector_2lep;
    std::vector < TH1F* > _theGenRelIsoVector_2lep;
    std::vector < TH1F* > _theGen_ntracks_2lep;
    std::vector < TH1F* > _theGen_Charge_2lep;
    std::vector < TH1F* > _theGenPt_2lep;
    std::vector < TH1F* > _theGenEta_2lep;
    std::vector < TH1F* > _thecosDphiLepGen_2lep;

    // std::map<int, std::vector<string>> _theCutsVectorMap;
    // std::map<int, std::vector<int>> _theCutFlowVectorMap;
    // std::map<int, std::vector<int>> _theCutFlowVectorMap_2lep;
   std::vector < string > _myTitles;
   std::vector < string > _myTitles2;
   std::vector < string > _myTitles_2lep;
   std::vector < string > _myElTitles;
   std::vector < string > _mySignalTitles;
   std::vector < string > _mygenTitles;
   std::vector < Color_t > _myColors;
   std::vector < Color_t > _myColors2;
   std::vector < string > _mySigColors;
   std::vector < TH1F* > _myVector;
   std::vector < TH1F* > _myMTMHTVector;
   std::vector < TH1F* > _myMTnewmetVector;
   std::vector < TH1F* > _myMTrawmetVector;
   std::vector < TH1F* > _myMT2WVector;
   std::vector < TH1F* > _myTopnessVector;
   std::vector < TH1F* > _myTopnessmodVector;
   std::vector < TH1F* > _myChi2Vector;
   std::vector < TH1F* > _myHTratioVector;
   std::vector < TH1F* > _myMinDPhiVector;
   std::vector < TH1F* > _myDRlepbVector;
   std::vector < TH1F* > _myleadbptVector;

   std::vector < TH1F* > _mySignalVector;
   std::vector < TH1F* > _mySignalMT2WVector;
   std::vector < TH1F* > _mySignalTopnessVector;
   std::vector < TH1F* > _mySignalTopnessmodVector;
   std::vector < TH1F* > _mySignalChi2Vector;
   std::vector < TH1F* > _mySignalHTratioVector;
   std::vector < TH1F* > _mySignalMinDPhiVector;
   std::vector < TH1F* > _mySignalDRlepbVector;
   std::vector < TH1F* > _mySignalleadbptVector;
   std::vector < TH1F* > _mySignalPZetaVis_TrkLep;
   std::vector < TH1F* > _mySignal_ak4NEFVector;
   std::vector < TH1F* > _mySignal_ak4CEFVector;
   std::vector < TH1F* > _mySignal_ak4EFVector;
   std::vector < TH1F* > _mySignalmetVector;
   std::vector < TH1F* > _mySignalmetphiVector;
   std::vector < TH1F* > _mySignalrawmetVector;
   std::vector < TH1F* > _mySignalrawmetphiVector;
   std::vector < TH1F* > _mySignallepptVector;
   std::vector < TH1F* > _mySignalleprelisoVector;
   std::vector < TH1F* > _mySignallepminirelisoVector;
   std::vector < TH1F* > _mySignallepabsisoVector;
   std::vector < TH1F* > _mySignallepminiabsisoVector;
   std::vector < TH1F* > _mySignallepetaVector;
   std::vector < TH1F* > _mySignallepphiVector;
   std::vector < TH1F* > _mySignalHTVector;
   std::vector < TH1F* > _mySignalnjetsVector;
   std::vector < TH1F* > _mySignalnhfjetsVector;
   std::vector < TH1F* > _mySignalnbjetsVector;
   std::vector < TH1F* > _mySignalnjets_pt200_nobtagsVector;
   std::vector < TH1F* > _mySignalleadISRjet_pt200_nobtagsVector;
   std::vector < TH1F* > _mySignalMEToverSqrtHTVector;
   std::vector < TH1F* > _mySignalMlepbVector;
   std::vector < TH1F* > _mySignalgenMlepbVector;
   std::vector < TH1F* > _mySignalM3bVector;
   std::vector < TH1F* > _mySignaljetptVector;
   std::vector < TH1F* > _mySignalDPhiLepJetVector;
   std::vector < TH1F* > _mySignalleadjetptVector;
   std::vector < TH1F* > _mySignalDPhiWLep;
   std::vector < TH1F* > _mySignalWptVector;
   std::vector < TH1F* > _mySignalPZeta_TrkLep;

   std::vector < TH1F* > _myVector2;
   std::vector < TH1F* > _myMT2WVector2;
   std::vector < TH1F* > _myTopnessVector2;
   std::vector < TH1F* > _myTopnessmodVector2;
   std::vector < TH1F* > _myChi2Vector2;
   std::vector < TH1F* > _myHTratioVector2;
   std::vector < TH1F* > _myMinDPhiVector2;
   std::vector < TH1F* > _myDRlepbVector2;
   std::vector < TH1F* > _myleadbptVector2;
   std::vector < TH1F* > _myPZetaVis_TrkLep2;
   std::vector < TH1F* > _my_ak4NEFVector2;
   std::vector < TH1F* > _my_ak4CEFVector2;
   std::vector < TH1F* > _my_ak4EFVector2;
   std::vector < TH1F* > _mymetVector2;
   std::vector < TH1F* > _mymetphiVector2;
   std::vector < TH1F* > _myrawmetVector2;
   std::vector < TH1F* > _myrawmetphiVector2;
   std::vector < TH1F* > _mylepptVector2;
   std::vector < TH1F* > _myleprelisoVector2;
   std::vector < TH1F* > _mylepminirelisoVector2;
   std::vector < TH1F* > _mylepabsisoVector2;
   std::vector < TH1F* > _mylepminiabsisoVector2;
   std::vector < TH1F* > _mylepetaVector2;
   std::vector < TH1F* > _mylepphiVector2;
   std::vector < TH1F* > _myHTVector2;
   std::vector < TH1F* > _mynjetsVector2;
   std::vector < TH1F* > _mynhfjetsVector2;
   std::vector < TH1F* > _mynbjetsVector2;
   std::vector < TH1F* > _mynjets_pt200_nobtagsVector2;
   std::vector < TH1F* > _myleadISRjet_pt200_nobtagsVector2;
   std::vector < TH1F* > _myMEToverSqrtHTVector2;
   std::vector < TH1F* > _myMlepbVector2;
   std::vector < TH1F* > _mygenMlepbVector2;
   std::vector < TH1F* > _myM3bVector2;
   std::vector < TH1F* > _myjetptVector2;
   std::vector < TH1F* > _myDPhiLepJetVector2;
   std::vector < TH1F* > _myleadjetptVector2;
   std::vector < TH1F* > _myDPhiWLepVector2;
   std::vector < TH1F* > _myWptVector2;
   std::vector < TH1F* > _myPZeta_TrkLepVector2;

   std::vector < TH1F* > _myDataVector;
   std::vector < TH1F* > _myDataMTMHTVector;
   std::vector < TH1F* > _myDataMTnewmetVector;
   std::vector < TH1F* > _myDataMTrawmetVector;
   std::vector < TH1F* > _myDataMT2WVector;
   std::vector < TH1F* > _myDataTopnessVector;
   std::vector < TH1F* > _myDataTopnessmodVector;
   std::vector < TH1F* > _myDataChi2Vector;
   std::vector < TH1F* > _myDataHTratioVector;
   std::vector < TH1F* > _myDataMinDPhiVector;
   std::vector < TH1F* > _myDataDRlepbVector;
   std::vector < TH1F* > _myDataleadbptVector;
   std::vector < TH1F* > _myDataPZetaVis_TrkLep;
   std::vector < TH1F* > _myData_ak4NEFVector;
   std::vector < TH1F* > _myData_ak4CEFVector;
   std::vector < TH1F* > _myData_ak4EFVector;
   std::vector < TH1F* > _myDatametVector;
   std::vector < TH1F* > _myDatametphiVector;
   std::vector < TH1F* > _myDatarawmetVector;
   std::vector < TH1F* > _myDatarawmetphiVector;
   std::vector < TH1F* > _myDatajecmetVector;
   std::vector < TH1F* > _myDatajecmetXVector;
   std::vector < TH1F* > _myDatajecmetYVector;
   std::vector < TH1F* > _myDatajecmetphiVector;
   std::vector < TH1F* > _myDataunjecmetVector;
   std::vector < TH1F* > _myDataunjecmetphiVector;
   std::vector < TH1F* > _myDatacalometVector;
   std::vector < TH1F* > _myDatacalometphiVector;
   std::vector < TH1F* > _myDatatrkmetVector;
   std::vector < TH1F* > _myDatatrkmetphiVector;
   std::vector < TH1F* > _myDatalepptVector;
   std::vector < TH1F* > _myDataleprelisoVector;
   std::vector < TH1F* > _myDatalepminirelisoVector;
   std::vector < TH1F* > _myDatalepabsisoVector;
   std::vector < TH1F* > _myDatalepminiabsisoVector;
   std::vector < TH1F* > _myDatalepetaVector;
   std::vector < TH1F* > _myDatalepphiVector;
   std::vector < TH1F* > _myDataHTVector;
   std::vector < TH1F* > _myDataNGoodVtxVector;
   std::vector < TH1F* > _myDatanjetsVector;
   std::vector < TH1F* > _myDatanhfjetsVector;
   std::vector < TH1F* > _myDatanbjetsVector;
   std::vector < TH1F* > _myDatanjets_pt200_nobtagsVector;
   std::vector < TH1F* > _myDataleadISRjet_pt200_nobtagsVector;
   std::vector < TH1F* > _myDataMEToverSqrtHTVector;
   std::vector < TH1F* > _myDataMlepbVector;
   std::vector < TH1F* > _myDatagenMlepbVector;
   std::vector < TH1F* > _myDataM3bVector;
   std::vector < TH1F* > _myDatajetptVector;
   std::vector < TH1F* > _myDatajetphiVector;
   std::vector < TH1F* > _myDataDPhiLepJetVector;
   std::vector < TH1F* > _myDataleadjetptVector;
   std::vector < TH1F* > _myDataDPhiWLep;
   std::vector < TH1F* > _myDataWptVector;
   std::vector < TH1F* > _myDataPZeta_TrkLep;
   std::vector < TH1F* > _myDataak4NEFVector;
   std::vector < TH1F* > _myDataak4CEFVector;
   std::vector < TH1F* > _myDataak4EFVector;
   std::vector < TH1F* > _myDatadetainVector;
   std::vector < TH1F* > _myDatadphiinVector;
   std::vector < TH1F* > _myDatasigmaietaietaVector;
   std::vector < TH1F* > _myDatahovereVector;
   std::vector < TH1F* > _myDatadzVector;
   std::vector < TH1F* > _myDatad0Vector;
   std::vector < TH1F* > _myDataempVector;
   std::vector < TH1F* > _myDataminirelisoVector;
   std::vector < TH1F* > _myDatamissinghitsVector;
   std::vector < TH1F* > _myDataconversionsvetoVector;
};
#endif
